### ISSUE TITLE
Update Personal Profile Request backend API

### ISSUE THREAD

**Issue by Radwan-Albahrani** [bepitome/flutter-file-storage-challenge#8]
**Is your feature request related to a problem? Please describe.**
I cannot currently Update Personal Information through the backend. Creating New User does not work due to same physical ID. And there is no API command to update specific personal information

**Describe the solution you'd like**
A new API request to allow for editing of personal Informatione.

**Comment by mutairibassam** [comment]
@Radwan-Albahrani thanks for reporting the issue, I understand your situation and backend behavior. There are two ways to be implemented, and let me know which one you think it's better for frontend.

1. Putting a flag in create request header or body which indicates to the expected behavior.

- Headers example:
```yml
# for example:
# endpoint: /multipart/create
headers:
  x-physical-id: xxxxxxxxxxxxxxxxx,
  x-create-user: x  # if it's set to `x` it will create a new user, if the header is not exist it will update the record.
```
- Body example:
```yml
# for example:
# endpoint: /multipart/create
"body": {
  "create": true  # if it's set to `true` it will create a new user, if it's set to false it will update the record.
}
```
---
2. Develop a separate endpoint to handle update profile.

Or if you have any kind of implementation please share.
